// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ShimebaMvcAPI.Models.IndoorIO
{

    public class Attrs
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("tags")]
        public string Tags { get; set; }

        [JsonProperty("food")]
        public string Food { get; set; }

        [JsonProperty("drinks")]
        public string Drinks { get; set; }

        [JsonProperty("featureId")]
        public long? FeatureId { get; set; }

        [JsonProperty("_referenceLocation")]
        public string ReferenceLocation { get; set; }
    }

}
