// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ShimebaMvcAPI.Models.IndoorIO
{

    public class GeomType
    {

        [JsonProperty("Class")]
        public string Class { get; set; }

        [JsonProperty("Accessible")]
        public Accessible Accessible { get; set; }

        [JsonProperty("Width")]
        public Width Width { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }

        [JsonProperty("Wall height")]
        public WallHeight WallHeight { get; set; }

        [JsonProperty("Color")]
        public Color Color { get; set; }

        [JsonProperty("Inherit wall color from area")]
        public InheritWallColorFromArea InheritWallColorFromArea { get; set; }

        [JsonProperty("Wall texture")]
        public WallTexture WallTexture { get; set; }

        [JsonProperty("Railing support distance")]
        public RailingSupportDistance RailingSupportDistance { get; set; }

        [JsonProperty("Texture")]
        public Texture Texture { get; set; }

        [JsonProperty("Height")]
        public Height Height { get; set; }

        [JsonProperty("Railing color")]
        public RailingColor RailingColor { get; set; }

        [JsonProperty("Railing glass opacity")]
        public RailingGlassOpacity RailingGlassOpacity { get; set; }

        [JsonProperty("Railing glass color")]
        public RailingGlassColor RailingGlassColor { get; set; }

        [JsonProperty("Glass bottom height")]
        public GlassBottomHeight GlassBottomHeight { get; set; }

        [JsonProperty("Glass top height")]
        public GlassTopHeight GlassTopHeight { get; set; }

        [JsonProperty("Glass opacity")]
        public GlassOpacity GlassOpacity { get; set; }

        [JsonProperty("Glass color")]
        public GlassColor GlassColor { get; set; }

        [JsonProperty("Wall width")]
        public WallWidth WallWidth { get; set; }

        [JsonProperty("Wall color")]
        public WallColor WallColor { get; set; }

        [JsonProperty("Glass texture")]
        public GlassTexture GlassTexture { get; set; }

        [JsonProperty("Length")]
        public Length Length { get; set; }

        [JsonProperty("Doorway height")]
        public DoorwayHeight DoorwayHeight { get; set; }

        [JsonProperty("Door height")]
        public DoorHeight DoorHeight { get; set; }

        [JsonProperty("Glass height")]
        public GlassHeight GlassHeight { get; set; }

        [JsonProperty("FloorHeight")]
        public FloorHeight FloorHeight { get; set; }

        [JsonProperty("Side walls")]
        public SideWalls SideWalls { get; set; }

        [JsonProperty("Floor texture")]
        public FloorTexture FloorTexture { get; set; }

        [JsonProperty("Floor opacity")]
        public FloorOpacity FloorOpacity { get; set; }
    }

}
