// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ShimebaMvcAPI.Models.IndoorIO
{

    public class Properties
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("level")]
        public int Level { get; set; }

        [JsonProperty("accessible")]
        public bool Accessible { get; set; }

        [JsonProperty("attrs")]
        public Attrs Attrs { get; set; }

        [JsonProperty("geomType")]
        public GeomType GeomType { get; set; }

        [JsonProperty("i1")]
        public int? I1 { get; set; }

        [JsonProperty("i2")]
        public int? I2 { get; set; }

        [JsonProperty("connector")]
        public bool? Connector { get; set; }

        [JsonProperty("direction")]
        public int? Direction { get; set; }

        [JsonProperty("levelup")]
        public int? Levelup { get; set; }

        [JsonProperty("leveldown")]
        public int? Leveldown { get; set; }
    }

}
