// <auto-generated />
namespace MallBuddyApi2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class polypoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(polypoi));
        
        string IMigrationMetadata.Id
        {
            get { return "201404131459494_poly-poi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
