// <auto-generated />
namespace MallBuddyApi2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class poislevels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(poislevels));
        
        string IMigrationMetadata.Id
        {
            get { return "201404092346212_poislevels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
